### ISSUE TITLE
Keep playlist in folder, and update newly added songs to it on-run

### ISSUE THREAD

**Issue by lang-eric** [FelixGail/PlayMusicDownloader#9]
So like if I have a folder representing my thumbs-up playlist, when I run the app, it downloads any new songs I might've added to the playlist on google's side.

**Comment by FelixGail** [comment]
Exactly.

**Comment by FelixGail** [comment]
Deleting Songs in your remote playlist will have no impact, though, since you could have multiple playlists in one folder and the script is not saving information like that.
